sonar.projectKey=student-portal
sonar.projectName=Student Portal Application
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/static/**,**/templates/**

sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xmlx``

sonar.sourceEncoding=UTF-8

# Write scanner metadata to repo root so quality-gate action finds report-task.txt
sonar.working.directory=../.scannerwork
sonar.scanner.metadataFilePath=../.scannerwork/report-task.txt
