apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: devopsdozo
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 879381241087.dkr.ecr.ap-south-1.amazonaws.com/augk8s26-backend:dafc1c583ef1f4fb2836569cc7f87ce1063b7cc4
        ports:
        - containerPort: 8000

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 3

        env:
        - name: DB_LINK
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_LINK
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: SECRET_KEY

        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD

        - name: ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: ALLOWED_ORIGINS
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: APP_VERSION
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME