# a opaque secret to store the db_link
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_LINK : cG9zdGdyZXNxbDovL3BnYWRtaW46Q2hhbmdlTWUxMjMhQHRpbnktcGcuY3ZpazhhY2N3MnRrLmFwLXNvdXRoLTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9teWRi