name: EKS 3 Tier Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'Kubernetes-world/3-tier-app/**'
  workflow_dispatch:

env:
  AWS_ACCOUNT_ID: 879381241087
  AWS_REGION: ap-south-1
  AWS_ROLE_ARN: arn:aws:iam::879381241087:role/aws-github-oidc-aug26
  ECR_REGISTRY: 879381241087.dkr.ecr.ap-south-1.amazonaws.com

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    strategy:
      matrix:
        services:
          - name: frontend
            path: 'Kubernetes-world/3-tier-app/src/frontend'
            ecr_repo: 'augk8s26-frontend'
          - name: backend
            path: 'Kubernetes-world/3-tier-app/src/backend'
            ecr_repo: 'augk8s26-backend'
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: aws creds with oidc
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ecr login
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
      # use github action cache
      - name: Build and Push ${{ matrix.services.name }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ env.ECR_REGISTRY }}/${{ matrix.services.ecr_repo }}:${{ github.sha }} \
            --cache-from type=registry,ref=${{ env.ECR_REGISTRY }}/${{ matrix.services.ecr_repo }}:buildcache \
            --cache-to type=registry,ref=${{ env.ECR_REGISTRY }}/${{ matrix.services.ecr_repo }}:buildcache,mode=max,image-manifest=true,oci-mediatypes=true \
            --push ${{ matrix.services.path }}
